FROM alpine:3.20

RUN apk add --no-cache ffmpeg \
    iproute2 \
    iptables \
    bash \
    tcpdump \
    net-tools \
    coreutils \
    curl \
    python3 

RUN mkdir -p /media /results /hls

COPY media/video_tfg.mp4 /media/video_tfg.mp4