{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wireguard.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wireguard.fullname" . }}-role
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wireguard.fullname" . }}-rolebinding
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wireguard.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "wireguard.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}
